/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.example.classes.man;
import org.example.classes.person;
import org.example.classes.personInvocationHandler;

import java.lang.reflect.Proxy;

public class App {

    public static void main(String[] args) {
        man ram = new man("ram","52","bbsr","india");
        ClassLoader ramclassloader = ram.getClass().getClassLoader();
        Class[] interfaces = ram.getClass().getInterfaces();
        person proxRam =(person) Proxy.newProxyInstance(ramclassloader,interfaces,new personInvocationHandler(ram));
        proxRam.introduction(ram.getName());
    }
}
